### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by Phlya** [YaqiangCao/cLoops#11]
Hi! This tools looks really interesting and I would like to give it a try. Is it possible to make input format more flexible? E.g. support the .pairs format from 4DN, and its extension from the Mirny?
https://github.com/4dn-dcic/pairix/blob/master/pairs_format_specification.md
lab https://pairtools.readthedocs.io/en/latest/formats.html

Or allow specification of which column in the data corresponds to what...

Converting such huge files takes a long time, considering they need to by un-gzipped and then gzipped agian. Thank you!

**Comment by YaqiangCao** [comment]
Hi Ilya,
     Thanks for your interest in cLoops, and it is quite a good suggestion
to support more popular and flexible input data format.
      However, I am current focusing on improving the algorithm as support
more kinds of data, such as Capture-HiC, and more accurate loop calling
related work, which should be more important to the general users.
      Thanks again for the suggestions. I will let you know when we do the
updates.
       Thanks.
Yaqiang
