### ISSUE TITLE
Some details about the parameter 'eps'

### ISSUE THREAD

**Issue by Paranoid-mike** [YaqiangCao/cLoops#12]
Hi Yaqiang, recently i'm dealing with a Hi-C data set,and since the sequencing depth of our data is not huge(about 80 Million Cis-PETs ), so i need to find the optimal "eps" and here is my question. If i specify the "eps" with a series of parameters, will the program returns the consensus loop called out at every "eps" or the simple merge of loops called out at every eps parameters. Thanks a lot :)

**Comment by zhqu1148980644** [comment]
cloops will output the loops with the highest significance among all loops overlapped produced by multi `eps`

**Comment by YaqiangCao** [comment]
> Hi Yaqiang, recently i'm dealing with a Hi-C data set,and since the sequencing depth of our data is not huge(about 80 Million Cis-PETs ), so i need to find the optimal "eps" and here is my question. If i specify the "eps" with a series of parameters, will the program returns the consensus loop called out at every "eps" or the simple merge of loops called out at every eps parameters. Thanks a lot :)



Dear user @Paranoid-mike , 
        Thanks for your interest of cLoops for calling loops, it will be a good choice for you over other tools~
        @zhqu1148980644  has give the right explanation, thanks! I will explain a little more. 
        For example, for your data, I suggest eps=5000,7500,10000 and minPts=5,10,20, so total there will be 3*3 clustering carried out to find potential loop regions,  candidate with PETs less than max(minPts) (here 20) will be filtered. Further, for overlapped loops, after the significance test, cLoops will output the one with highest significance by binomial test.  
       The reason for multiple times of clustering with eps and minPts is that,1) though DBSCAN clustering (or other) is great, there will be some random result due to the visit order of points, even though we try to control it; 2) no idea theory estimation of the parameters. 3) Hi-C data quality may different from one set to another. 
       Happy loop-calling. Hope your project data will work well. 
       Thanks. 
Best,
Yaqiang

**Comment by YaqiangCao** [comment]
> Hi Yaqiang, recently i'm dealing with a Hi-C data set,and since the sequencing depth of our data is not huge(about 80 Million Cis-PETs ), so i need to find the optimal "eps" and here is my question. If i specify the "eps" with a series of parameters, will the program returns the consensus loop called out at every "eps" or the simple merge of loops called out at every eps parameters. Thanks a lot :)

Dear user,
         If you find cLoops useful and the explanation make sense, please give a star at the github project~ Also, citation is quit well come as our cLoops has recently been accepted~.
Thanks.
Yaqiang

**Comment by Paranoid-mike** [comment]
Really appreciate for the clarification ：） @zhqu1148980644 @YaqiangCao
