### ISSUE TITLE
adjust parameters to increase/decrease stringency 

### ISSUE THREAD

**Issue by rikrdo89** [YaqiangCao/cLoops#13]
Hi, I am using cLoops to call loops on my HiC datasets (>200M valid pairs/sample), and I am trying to tune the parameters to incrase and or decrease the number of called loops. Could you explain how to use eps and minPts to increase the sensitivity of the calls? Also I noticed that the majority of the calls are less of a given distance apart... is there a way to incrase the distance to detect longer-range interactions? 

I have used -m 3 (equals -eps 5000,7500,10000 -minPts 20,30,40,50 -hic) but I am not sure how this works. Thank you.

**Comment by rikrdo89** [comment]
Thank you Yaqiang for this throughout response. I have run a few analysis, and the algorithm performs quite well.

I would want to understand a bit more how the eps parameter affects loop calls. I understand that the eps , as you define it,is the distance for two PETs to be considered neighbors. If the value of this parameter is large (say 10000),  does this mean that region that contain these peaks/loops is also larger? (i.e. a large square at the apex of a TAD) and if it is low (say 2500), the area surrounding the peak interacting PETs is smaller?

and for calculating the significance test, are the permutations done around the peak, or within the peak region?

**Comment by YaqiangCao** [comment]
> Thank you Yaqiang for this throughout response. I have run a few analysis, and the algorithm performs quite well.
> 
> I would want to understand a bit more how the eps parameter affects loop calls. I understand that the eps , as you define it,is the distance for two PETs to be considered neighbors. If the value of this parameter is large (say 10000), does this mean that region that contain these peaks/loops is also larger? (i.e. a large square at the apex of a TAD) and if it is low (say 2500), the area surrounding the peak interacting PETs is smaller?
> 
> and for calculating the significance test, are the permutations done around the peak, or within the peak region?

Yes, for larger eps, the final loop anchors will be larger. 

The permutations were done around the loops.

**Comment by YaqiangCao** [comment]
> Thank you Yaqiang for this throughout response. I have run a few analysis, and the algorithm performs quite well.
> 
> I would want to understand a bit more how the eps parameter affects loop calls. I understand that the eps , as you define it,is the distance for two PETs to be considered neighbors. If the value of this parameter is large (say 10000), does this mean that region that contain these peaks/loops is also larger? (i.e. a large square at the apex of a TAD) and if it is low (say 2500), the area surrounding the peak interacting PETs is smaller?
> 
> and for calculating the significance test, are the permutations done around the peak, or within the peak region?

Please give us a star at the github repo and cite our cLoops paper if it helps. Thanks!

**Comment by rikrdo89** [comment]
thank you for your explanation. Yes of course I will cite your paper. This tool is extremely helpful.
