### ISSUE TITLE
HiC input from TADbit

### ISSUE THREAD

**Issue by bontus** [YaqiangCao/cLoops#15]
Dear Yaqiang,

I am interested in using cLoops on our HiC data, which has been processed using TADbit and binless. Unfortunately, neither of these programs produces a BEDPE file, so I am a bit at a loss in terms of feeding this data to cLoops.

TADbit does create its own BED-llike .TSV format files with paired-end mapped reads, which in turn are used by binless, so I was wondering whether these could be re-formatted and used by cLoops.
I uploaded a sample file for testing purposes, see https://github.com/bontus/cLoops_TADbit/blob/master/FPR_5_both_map_chr10_sample.tsv

File format description (edited based on https://github.com/3DGenomes/binless)
TADbit .tsv: tab-separated text file containing paired-end mapped reads for a single experiment. All lines starting with # will be discarded. The order of the reads is unimportant. It has the following columns:

    id: ID of the mapped pair (alphanumeric without spaces)
    chr1: chromosome of read 1 (alphanumeric without spaces)
    pos1: position of the 5' end of read 1 (integer)
    strand1: whether the read maps on the forward (1) or reverse (0) direction
    length1: how many bases were mapped (integer)
    re.up1: upstream restriction site closest to pos1 (integer <= pos1)
    re.dn1: downstream restriction site closest to pos1 (integer > pos1)
    chr2: chromosome of read 2 (alphanumeric without spaces)
    pos2: position of the 5' end of read 2 (integer)
    strand2: whether the read maps on the forward (1) or reverse (0) direction
    length2: how many bases were mapped (integer)
    re.up2: upstream restriction site closest to pos2 (integer <= pos1)
    re.dn2: downstream restriction site closest to pos1 (integer > pos1)

As I have not worked with HiC-Pro, I do not know whether its BEDPE file provides information about the positions of restriction sites or not. In case the BEDPE files for cLoops solely contain information based on the id, chr1/2, pos1/2 and strand1/2 information, one could convert the TADbit TSVs to BEDPE using AWK:

```
TSVFILE=FPR_5_both_map_chr10_sample.tsv;
grep -v "[#~]" $TSVFILE \
  | awk -v OFS='\t' '{
    if ($4 == 1 && $10 == 1) {print $2,$3,$3+$5,$8,$9,$9+$11,$1,".\t+\t+";}
    if ($4 == 1 && $10 == 0) {print $2,$3,$3+$5,$8,$9-$11,$9,$1,".\t+\t-";}
    if ($4 == 0 && $10 == 1) {print $2,$3-$5,$3,$8,$9,$9+$11,$1,".\t-\t+";}
    if ($4 == 0 && $10 == 0) {print $2,$3-$5,$3,$8,$9-$11,$9,$1,".\t-\t-";}
    }'
```
One thing to note is TADbit's mapping, as reads can be split at the ligation site if they do not map entirely, which makes their files quite complex. An example can be seen here (after converting their TSV to SAM):

```
D00733:158:CA67GANXX:1:1211:12600:68498#1/6	0	chr10	305327	33	1M	=	430210	41	*	*	TC:i:1	E1:i:304175	E2:i:305356	E3:i:429917	E4:i:430247
D00733:158:CA67GANXX:1:1211:12600:68498#4/6	24	chr10	305327	33	1M	=	305359	-33	*	*	TC:i:1	E1:i:304175	E2:i:305356	E3:i:305356	E4:i:305474
D00733:158:CA67GANXX:1:1211:12600:68498#5/6	16	chr10	305327	33	1M	=	430250	-41	*	*	TC:i:1	E1:i:304175	E2:i:305356	E3:i:430247	E4:i:430302
D00733:158:CA67GANXX:1:1211:12600:68498~2~#2/6	0	chr10	305359	33	0M	=	430210	41	*	*	TC:i:2	E1:i:305356	E2:i:305474	E3:i:429917	E4:i:430247
D00733:158:CA67GANXX:1:1211:12600:68498~2~#6/6	0	chr10	305359	33	0M	=	430250	-41	*	*	TC:i:2	E1:i:305356	E2:i:305474	E3:i:430247	E4:i:430302
D00733:158:CA67GANXX:1:1211:12600:68498#4/6	24	chr10	305359	33	0M	=	305327	33	*	*	TC:i:1	E3:i:305356	E4:i:305474	E1:i:304175	E2:i:305356
D00733:158:CA67GANXX:1:1211:12600:68498#1/6	0	chr10	430210	41	1M	=	305327	33	*	*	TC:i:1	E3:i:429917	E4:i:430247	E1:i:304175	E2:i:305356
D00733:158:CA67GANXX:1:1211:12600:68498~2~#2/6	0	chr10	430210	41	1M	=	305359	-33	*	*	TC:i:2	E3:i:429917	E4:i:430247	E1:i:305356	E2:i:305474
D00733:158:CA67GANXX:1:1211:12600:68498#3/6	24	chr10	430210	41	1M	=	430250	-41	*	*	TC:i:1	E1:i:429917	E2:i:430247	E3:i:430247	E4:i:430302
D00733:158:CA67GANXX:1:1211:12600:68498~2~#6/6	0	chr10	430250	41	0M	=	305359	-33	*	*	TC:i:2	E3:i:430247	E4:i:430302	E1:i:305356	E2:i:305474
D00733:158:CA67GANXX:1:1211:12600:68498#5/6	16	chr10	430250	41	0M	=	305327	33	*	*	TC:i:1	E3:i:430247	E4:i:430302	E1:i:304175	E2:i:305356
D00733:158:CA67GANXX:1:1211:12600:68498#3/6	24	chr10	430250	41	0M	=	430210	41	*	*	TC:i:1	E3:i:430247	E4:i:430302	E1:i:429917	E2:i:430247
```
Let me know what you think, it would be great if we can solve this issue and make cLoops work with TADbit too.

Kind regards

edit: fixed the code

**Comment by YaqiangCao** [comment]
Hi dear user,
    Thanks for your interest of cLoops, and provide such detail
explanations of TADbit output and examples.
     Regarding your question, I think your bash script with AWK
converting TADbit
TSVs to BEDPE is great, that BEDPE file can be input of cLoops.
     Regarding the reads splitted at the ligation site , what about the
percentage? If the percentage like <10%, I think we can ignore it.
Alternatively, we can just add a BEDPE record for the ligation site, as
long as it is paired.  In pre-processing BEDPE file, cLoops actually check
the centers of  PETs to keep unique PETs for clustering, as in code:
if (pet.cA, pet.cB) in chroms[pet.chromA]["r"]:
continue
     Please let me know if you have further concerns.
     Thanks.
Best,
Yaqiang.

**Comment by bontus** [comment]
Dear Yaqiang,
Thanks for the advice, I am currently running cLoops with the BEDPE files from TADbit even though the split reads make up quite a high percentage (20%+) at times, so I might have to repeat this later on. So far, everything seems to work fine, but just to make sure: I split the TSV files by chromosome and thus am running each chromosome separately, is that OK for cLoops?
Best

**Comment by YaqiangCao** [comment]
Hi dear user,
   Run each chromosome separately for cLoops is absolutely OK.  I often use
chr21 in human to test parameters.
   It will only affect if you use jd2washU
<https://github.com/YaqiangCao/cLoops/blob/master/scripts/jd2washU> or
jd2juice <https://github.com/YaqiangCao/cLoops/blob/master/scripts/jd2juice> if
you try to convert the cLoops tmp data directory to .hic or washU
long-range track, as only one chromosome will be generated.
Best,
Yaqiang
