### ISSUE TITLE
tuning parameters for stripe calls ( callStripes )

### ISSUE THREAD

**Issue by rikrdo89** [YaqiangCao/cLoops#16]
Hi, 
I was wondering if you could provide more information on how to use the different parameters in callStripes to optimize the calls. I run it on my data using default parameters and while I notice there are some calls that are accurate, many of them are not visually obvious. The algorithm is also missing stripes that tend to be longer and wider.
 I am attaching some screenshots.

![image](https://user-images.githubusercontent.com/24930604/71911428-a9d27a00-3141-11ea-9b27-d27e68b346e9.png)

![image](https://user-images.githubusercontent.com/24930604/71911454-b6ef6900-3141-11ea-9b66-27d6236c63fb.png)

![image](https://user-images.githubusercontent.com/24930604/71911477-beaf0d80-3141-11ea-9de6-ecbd55c5a59d.png)

**Comment by YaqiangCao** [comment]
> Hi,
> I was wondering if you could provide more information on how to use the different parameters in callStripes to optimize the calls. I run it on my data using default parameters and while I notice there are some calls that are accurate, many of them are not visually obvious. The algorithm is also missing stripes that tend to be longer and wider.
> I am attaching some screenshots.
> 
> ![image](https://user-images.githubusercontent.com/24930604/71911428-a9d27a00-3141-11ea-9b27-d27e68b346e9.png)
> 
> ![image](https://user-images.githubusercontent.com/24930604/71911454-b6ef6900-3141-11ea-9b66-27d6236c63fb.png)
> 
> ![image](https://user-images.githubusercontent.com/24930604/71911477-beaf0d80-3141-11ea-9de6-ecbd55c5a59d.png)

Dear User, 
      The parameters as default were determined by HiChIP H3K27ac data, of which the stripes could be more kind of "sharp" compared to Hi-C data I guess. 
      Could you also please show me some examples the stripes were well called? 
      For how to tune key parameters , hope following explanations could help. 
      Increase the key parameter -eps from 20000 to 50000 may leads to longer and wider stripes. 
      Additionally, I would suggest ignore the significant flag as the last column of .strip file ([example](https://github.com/YaqiangCao/cLoops_supplementaryData/blob/master/examples/K562_HiChIP_H3K27ac_chr21_x_horizontal.stripe) ), convert all called potential stripes to juicebox visible file and determine your cutoffs, and then modify the code of [callStripes](https://github.com/YaqiangCao/cLoops/blob/master/scripts/callStripes) from line 226-255 to set your cutoffs. 
      Hope this will be helpful. 
      Could you please email me some example data if you think it's better for me to determine the parameters? BEDPE format for small chromosome such as chr21 would be great. 
Best,
Yaqiang

**Comment by rikrdo89** [comment]
Thanks a lot Yaqiang for your suggestions and help! I am attaching the jd file for chr19 (mm10) from calling loops that I used for calling stripes.

I would also try increasing the eps parameter and see if there is any improvement. Could you also explain what the -ext  mean and whether increasing could also help ? 

[chr19-chr19.zip](https://github.com/YaqiangCao/cLoops/files/4031931/chr19-chr19.zip)

**Comment by rikrdo89** [comment]
Hi Yaqiang,
I tried running callStripes with the -eps parameter, but it is crashing no matter what value I give to this parameters (even providing the default value of 20000 fails) . I get a long list of errors, but I am taking a screenshot of what I think are the key errors.

I am using: 
```
$ conda list -n cLoops | grep joblib
joblib                    0.11                     py27_0    conda-forge

$ cLoops -v
cLoops v0.92
```
( I think the cLoops version is actually 0.93 according to the setup.py file, but your -v parameter calls a different version)

![image](https://user-images.githubusercontent.com/24930604/71924859-d1cfd680-315d-11ea-8f41-8b1b8bbd5beb.png)

![image](https://user-images.githubusercontent.com/24930604/71924894-e0b68900-315d-11ea-9c94-079f69f61aa2.png)

**Comment by YaqiangCao** [comment]
-ext option means to enlarge the another axis, to make the stripe region as a rectangle (a loop), it will help. 

For the bug, I have made some modifications to the code (add the type=int for input eps and minPts) and push it to the repo. Could you please clone the new code and try?  For your data, other eps can run successfully with modifications.
