### ISSUE TITLE
Distance cut-off

### ISSUE THREAD

**Issue by jessakay** [YaqiangCao/cLoops#17]
It seems like in a recent commit the threshold to distinguish inter-ligation and self-ligation PETs was set to 0 regardless of the input data. Is this the intended behavior?

https://github.com/YaqiangCao/cLoops/blob/3ea8b4c308a93481cd17a25d9d43ff9cca4a7736/cLoops/pipe.py#L284

**Comment by YaqiangCao** [comment]
Dear User, 
        Yes, the distance cutoff for PETs to estimate candidate loop significance was set to 0, this is a intended behavior. 
        Before that setting, loops were filtered by the estimated self-ligation distance 
https://github.com/YaqiangCao/cLoops/blob/3ea8b4c308a93481cd17a25d9d43ff9cca4a7736/cLoops/pipe.py#L281 
        Why I set this cut to 0:
        1) It will indeed slow down the programme for estimation of candidate loop significance, drawback; 
        2) If cut was estimated too big, such as 100k, then loops with distance like 120k will be all significant. 
        3) Using 0 will call a fewer more reliable loops, especially for Trac-looping data. 
        4) If cut was estimated too high, the distant loops with wider anchor length will be easy to get significant, however is visually check in heatmap, not that obvious.   
         Please let me know if you have any more concern.  If cut > 0 indeed work well in your data, please let me know. 
Best,
Yaqiang 
 
> It seems like in a recent commit the threshold to distinguish inter-ligation and self-ligation PETs was set to 0 regardless of the input data. Is this the intended behavior?
> 
> https://github.com/YaqiangCao/cLoops/blob/3ea8b4c308a93481cd17a25d9d43ff9cca4a7736/cLoops/pipe.py#L284

**Comment by jessakay** [comment]
Ah I see, that makes sense. I will let you know if I notice any big discrepancies. Thanks.
