### ISSUE TITLE
Conda env create issue

### ISSUE THREAD

**Issue by xinyangbing** [YaqiangCao/cLoops#19]
Hi when I run the conda env create line this happens:

"conda env create --name cLoops --file cLoops_env.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - sip==4.19.8=py27hf484d3e_0
  - readline==7.0=h7b6447c_5
  - xz==5.2.4=h14c3975_4
  - tk==8.6.8=hbc83047_0
  - gstreamer==1.14.0=hb453b48_1
  - mkl_fft==1.0.12=py27ha843d7b_0
  - libedit==3.1.20181209=hc058e9b_0
  - libxml2==2.9.9=he19cac6_0
  - ncurses==6.1=he6710b0_1
  - libffi==3.2.1=hd88cf55_4
  - scipy==1.2.1=py27h7c811a0_0
  - kiwisolver==1.1.0=py27he6710b0_0
  - glib==2.56.2=hd408876_0
  - pandas==0.24.2=py27he6710b0_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libgcc-ng==8.2.0=hdf63c60_1
  - statsmodels==0.9.0=py27h035aef0_0
  - joblib==0.11=py27_0
  - pyqt==5.9.2=py27h05f1152_2
  - dbus==1.13.6=h746ee38_0
  - libpng==1.6.37=hbc83047_0
  - libxcb==1.13=h1bed415_1
  - mkl_random==1.0.2=py27hd81dba3_0
  - matplotlib==2.2.3=py27hb69df0a_0
  - numpy-base==1.16.3=py27hde5b4d6_0
  - qt==5.9.7=h5867ecd_1
  - python==2.7.16=h9bab390_0
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - jpeg==9b=h024ee3a_2
  - fontconfig==2.13.0=h9420a91_0
  - expat==2.2.6=he6710b0_0
  - pcre==8.43=he6710b0_0
  - tornado==5.1.1=py27h7b6447c_0
  - libstdcxx-ng==8.2.0=hdf63c60_1
  - cycler==0.10.0=py27hc7354d3_0
  - freetype==2.9.1=h8a8886c_1
  - libuuid==1.0.3=h1bed415_2
  - subprocess32==3.5.3=py27h7b6447c_0
  - singledispatch==3.4.0.3=py27_0
  - numpy==1.16.3=py27h7e9f1db_0
  - openssl==1.1.1b=h7b6447c_1
  - zlib==1.2.11=h7b6447c_3
  - icu==58.2=h9c2bf20_1
  - sqlite==3.28.0=h7b6447c_0"

This seems to be an issue of certain versions not being available in Osx64 vs Linux64. Please help.

**Comment by YaqiangCao** [comment]
Dear User,
     May I ask what python and conda version you are using?
     If do not use the conda env settings, necessary packages I think are
joblib (0.11), scipy, numpy, seaborn, matplotlib, you can install the these
packages through conda, then python setup.py to install cLoops.
Best,
Yaqiang

**Comment by shakbarali** [comment]
OpenSSL is required

**Comment by xinyangbing** [comment]
I am using Python 3.7.3 and conda 4.8.3

**Comment by YaqiangCao** [comment]
Dear user,
     Please use conda create a environment for Pyhton2.7, cLoops only
support Python2.7. Then I think it will works well.
Best,
Yaqiang

**Comment by xinyangbing** [comment]
Hi Yaqiang,
Actually it still gave back an error and did not run. Could it be the conda version also?

**Comment by YaqiangCao** [comment]
Please try following:
conda create --name py2 python=2.7
conda activate py2
#then install joblib, matplotlib, scipy, seaborn through
conda install joblib==0.11
#then install cLoops with setup.py
python setup.py install

If not working, please show me the error info.
Thank you.

**Comment by xinyangbing** [comment]
Hi Yaqiang,
It worked, but I had to use pip to install joblib==0.11. Conda does not seem to have that version in their cloud anymore. Thank you for the help!

________________________________

**Comment by YaqiangCao** [comment]
Great.
