### ISSUE TITLE
Strand information

### ISSUE THREAD

**Issue by ozturan** [YaqiangCao/cLoops#2]
Hi,

I just wanted ask a quick question about the strand information. Is it required to specify the strand in the input .bedpe file? Or is it enough to provide chr1-start1-end1-chr2-start2-end2-score?

Thank you.

Dogancan

**Comment by YaqiangCao** [comment]
Please added the strand info and other information as required by BEDPE in our readme. The strand info was used to estimate a auto EPS for ChIA-PET data. And for HiChIP, actually not affect the result. So if you actually don't have the strand info, you can make it up as + or -. For example as following:
'chr19\t270000\t275000\tchr19\t280000\t285000\t13\t.\t+\t+\n'
