### ISSUE TITLE
How to plot the loops in WashU

### ISSUE THREAD

**Issue by r78v10a07** [YaqiangCao/cLoops#22]
Hi,
I've generated loops and I've got the SAMPLE_washU.txt file.
Which option in the WashU Genome Browser I should use to the the loops in a track?
Thanks,
Roberto

**Comment by YaqiangCao** [comment]
The legacy one : http://epigenomegateway.wustl.edu/legacy/
Upload through App->file upload as interaction / long-range interaction
data.
