### ISSUE TITLE
Extracting enrichment score from a matrix given a list of loops

### ISSUE THREAD

**Issue by rikrdo89** [YaqiangCao/cLoops#25]
This is a question. After generating a list of loops for a given hic matrix file, is there any way using cLoops to get the enrichment score of the same loop coordinates across another matrix file for comparison purposes? If not possible, could you suggest any tool for this? Thank you.

**Comment by YaqiangCao** [comment]
> This is a question. After generating a list of loops for a given hic matrix file, is there any way using cLoops to get the enrichment score of the same loop coordinates across another matrix file for comparison purposes? If not possible, could you suggest any tool for this? Thank you.

cLoops2 can do that in a new designed module, however it is still under developing and will be released in github soon.  I do not know if other tools can do that.
