### ISSUE TITLE
call stripe example file has error 

### ISSUE THREAD

**Issue by runningsnail2333** [YaqiangCao/cLoops#26]
hi YaQiang!
when I download  stripe example file  and run the code,and the error said the file is not correct .
but I can't find these file in example file ,
plese help thanks !

**Comment by YaqiangCao** [comment]
> hi YaQiang!
> when I download stripe example file and run the code,and the error said the file is not correct .
> but I can't find these file in example file ,
> plese help thanks !

Hi Dear User, 
     We did not provide the test for calling stripes.  I think it's better to run on your test data directly. 
Thank you. 
Best,
Yaiqang
