### ISSUE TITLE
cLoops differential loop calling

### ISSUE THREAD

**Issue by maharshi14** [YaqiangCao/cLoops#28]
Hi,

This is an enhancement issue.

Can the output of cLoops be somehow made compatible with existing differential loop callers, e.g. diffloop? 

Thank you,

Rishi

**Comment by YaqiangCao** [comment]
> Hi,
> 
> This is an enhancement issue.
> 
> Can the output of cLoops be somehow made compatible with existing differential loop callers, e.g. diffloop?
> 
> Thank you,
> 
> Rishi

Hi Rishi, 
      Thank you for the suggestions. 
       cLoops2, which is undering developing and will be releasesd soon, will have the feature to call differential enriched loops.  Extensive functions will be also included. 
Best,
Yaqiang
