### ISSUE TITLE
using cloops from Juicer 

### ISSUE THREAD

**Issue by yamzaleg** [YaqiangCao/cLoops#29]
Hello I used Juicer to preprocess my data and make .hic files. I am trying to use different loop calling tools to get a sense of what are the most confident loops in my dataset. I know that the input files for cLoops are .bedpe files, I'm wondering if you have a pipeline from Juicer to cloops. 

If you don't, I'm wondering how you pre-process the fastq files prior to running cLoops. 

Thank you so much,

Yonatan

**Comment by YaqiangCao** [comment]
Please refer to Hic-Pro for pre-processing, the a script in cLoops called
hicpropairs2bedpe can be used. Good luck.

yamzaleg ***@***.***>于2021年7月2日 周五下午3:14写道：

**Comment by yamzaleg** [comment]
Thank you so much for your reply. As I have already aligned the files using Juicer, is there a way to convert one of the output files to something I can use in cLoops? (I know you probably can't convert a .hic to a .bedpe file).

Thank you again,
Yonatan
