### ISSUE TITLE
Loops Visualization

### ISSUE THREAD

**Issue by yussufhajjaj** [YaqiangCao/cLoops#30]
Dear Yaqiang,

I've fed cLoops a HiChIP bedpe file from a hicpro allvalidpairs file. 

commands I used: cLoops -f "input files" -o hichip -m 4 -j -s -w -p -1. Then jd2washU, 

Now I have the terminal file processed by tabix and was able to visulaize it on washU. The thing is what I was able to visualize is a TAD like interaction desnity "pic 1", but not "loops", is there a way to have/visulize a loops file? and Thanks in advance.

pic 1: 
![denseTAD_Intragenic_smad3](https://user-images.githubusercontent.com/80690849/124433764-675c1e80-dd73-11eb-840c-9efc0e1cce00.JPG)

-Yussuf

**Comment by YaqiangCao** [comment]
Hi Yusuf,
       There should be a _washU.txt file, which can be load in legacy washU
genome browser for loops visualization.

yussufhajjaj ***@***.***>于2021年7月5日 周一上午3:30写道：

**Comment by yussufhajjaj** [comment]
yes I have the file, but couldn't locate where to upload in the washU, can you please guide me in this?

**Comment by yussufhajjaj** [comment]
I was able to visulaize the loops through this browser: http://epigenomegateway.wustl.edu/legacy/, I think it is the legacy that you mentioned. They look good! I don't know if there is a way to merge the two figures, the heat map one with this loops in the legacy? 

-yussuf
![EYS_locus](https://user-images.githubusercontent.com/80690849/124456160-ad70ac80-dd8a-11eb-8328-0e778d75636f.JPG)

**Comment by yussufhajjaj** [comment]
I was able to visulaize the loops through this browser: http://epigenomegateway.wustl.edu/legacy/, I think it is the legacy that you mentioned. They look good! I don't know if there is a way to merge the two figures, the heat map one with this loops in the legacy?

-yussuf
![EYS_locus_cloops](https://user-images.githubusercontent.com/80690849/124456465-04768180-dd8b-11eb-8583-ee2a006959f8.jpg)

**Comment by yussufhajjaj** [comment]
R code to generate a long range tab-delimited text file suitable for the normal washU browser, in case someone needs it.

from this format: 
chr5:172717363-172724489	chr5:172990243-173012824	1
to this format: 
chr1    713605  715737  chr1:720589-722848,2. 

####
library("tidyr")
library("stringr")

x <- read.table(file = "a_loops_washU.txt",sep = "\t" )

#to separate chr from the coordinates
a.sep <- separate(x, 
                    col = 1, 
                    sep = ":", 
                    into = c("chr", "strtend"))

#separate the coordinates into two different columns
a.sep2 <- separate(a.sep, 
                   col = "strtend" , 
                   sep = "-", 
                   into = c("strt", "end"))

#to add the score to the the second coordinates plus the comma
a.sep2$Z <- paste(a.sep2$V2, ",1", sep = "")

endproduct <- a.sep2[,c(1,2,3,6)]

write.table(endproduct, file= "washUfile_wwww.txt" , sep = "\t", row.names = F, col.names = F, quote = F)
####

Load as a text long range file, and change the configuration from heatmap to arc.

-yussuf

**Comment by YaqiangCao** [comment]
Thank you!

yussufhajjaj ***@***.***>于2021年7月5日 周一上午8:53写道：
