### ISSUE TITLE
cLoops: error: unrecognized arguments: 1 1 1

### ISSUE THREAD

**Issue by shenscore** [YaqiangCao/cLoops#5]
cLoops -f GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe.gz -o chiapet -w 1 -j 1 -s 1

usage: cLoops [-h] -f FNIN -o FNOUT [-m {0,1,2,3,4}] [-eps EPS]
              [-minPts MINPTS] [-p CPU] [-c CHROMS] [-w] [-j] [-s] [-hic]
              [-cut CUT] [-plot] [-v]
cLoops: error: unrecognized arguments: 1 1 1

**Comment by shenscore** [comment]
> 
> 
> Dear user,
> Since v0.91, when using -w -j -s , please directly call them as following.
> cLoops -f GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe.gz -o chiapet -w -j -s

Hi ! I git clone cLoops and reinstall:

cLoops -f GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe.gz -o chiapet -w -j -s
2018-11-27 11:16:29,177 INFO Command line: cLoops -f GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe.gz -o chiapet -m 0 -eps 0 -minPts 0 -p 1 -w True -j True -s True -c  -hic False -cut 0 -plot False -max_cut False
2018-11-27 11:16:29,177 ERROR minPts not assigned!

**Comment by nefclan** [comment]
> cLoops -f GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe.gz -o chiapet -w -j -s

In default cLoops uses user defined eps and minPts, you need to add -eps {EPS} and -minPts {MINPTS}. 

>-m {0,1,2,3,4}
>                  Pre-set parameters and signicicance cutoff for different
>                  types of data. Default is 0, using values from -eps and
>                  -minPts. Set 1 for sharp peak like ChIA-PET data
>                  (CTCF,RAD21,eg..),set 2 for broad peak like ChIA-PET data
>                  (H3K27ac,H3K4me1 eg..), and set 3 for deep sequenced Hi-C
>                  (>200 million cis PETs), set 4 for HiChIP (>100 million cis
>                  PETs). Detail parameters will be logged in the log file.

If you want to use pre-set eps and minPts for ChIA-PET data you need to set -m 1.
