### ISSUE TITLE
How to prepare the bedpe format file?

### ISSUE THREAD

**Issue by tiramisutes** [YaqiangCao/cLoops#6]
Hi,
It's an interest new tools.  But How to prepare the bedpe format file to input this software?
I have to try using HiCcompare to change the HiC-Pro resulted. However, It's still different from the example data (GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe).
Thanks.

**Comment by YaqiangCao** [comment]
Dear user,
         Please find [hicpropairs2bedpe] (https://github.com/YaqiangCao/cLoops/blob/master/scripts/hicpropairs2bedpe) to convert HiC-Pro output to bedpe. 
Best,
Yaqiang

**Comment by tiramisutes** [comment]
Ok，Thanks！
