### ISSUE TITLE
missing output with only jd2 files

### ISSUE THREAD

**Issue by kkkaiqiang** [YaqiangCao/cLoops#7]
I'm running cLoops with two bedpe files with the following commands:

> 2018-12-10 11:30:11,918 INFO Command line: cLoops -f /home/ykq/Data/BL-Hi-C/BL01/bl01.rmdup.bedpe,/home/ykq/Data/BL-Hi-C/BL02/bl02.rmdup.bedpe -o run2 -m 0 -eps 1000,2500,5000,7500,10000 -minPts 10,15,20 -p 10 -w True -j True -s False -c  -hic True -cut 0 -plot True -max_cut False
2018-12-10 11:30:11,918 INFO mode:0	 eps:[1000, 2500, 5000, 7500, 10000]	 minPts:[20, 15, 10]	 hic:True	

And there were only *.jd and *_disCutoff.pdf files, no loops file.

i wonder how  i can get the loops from these results, or should i rerun the data?

cLoops,log file attached.
[cLoops.log](https://github.com/YaqiangCao/cLoops/files/2674210/cLoops.log)

**Comment by YaqiangCao** [comment]
Dear User,
       According to the log, I can only judge that cLoops hasn't finished the running, so there is no result for .loop file. 
       I suggesting first using -c chr21 -cut 2000 to try see if cLoops can capture some significant loops. 
      Look forward to your feedback. 
Best,
Yaqiang

**Comment by kkkaiqiang** [comment]
> 
> 
> Dear User,
> According to the log, I can only judge that cLoops hasn't finished the running, so there is no result for .loop file.
> I suggesting first using -c chr21 -cut 2000 to try see if cLoops can capture some significant loops.
> Look forward to your feedback.
> Best,
> Yaqiang

Yaqiang,
Thanks a lot. I reran using -c chr21 -cut 2000 and it worked fine. 
Is it possible that the input bedpe files were too big(20+G) so it crashed before finishing the p-values calculating? The input files are HiC data. Would specifying less eps parameters help?

**Comment by YaqiangCao** [comment]
Dear User, 
        What is the memory of you computer/server? If the memory are limited, then the crash could caused by the too big data. 
        However, from the estimated self-ligation vs. inter-ligation distance cutoff in the log file, I figure may be the data have a lot close PETs (such as within 10kb) ? I would suggest run -cut 2000 or 10000 for trial to get distant loops (also remove close PETs to save memory). Otherwise if you want close loops, then keep -cut small. 
        If you could give the chr21 data, I can adjust a parameter for you. 
        If you find cLoops nice for your data, please give us a star at github and cite it~
Best,
Yaqiang

**Comment by YaqiangCao** [comment]
> > Dear User,
> > According to the log, I can only judge that cLoops hasn't finished the running, so there is no result for .loop file.
> > I suggesting first using -c chr21 -cut 2000 to try see if cLoops can capture some significant loops.
> > Look forward to your feedback.
> > Best,
> > Yaqiang
> 
> Yaqiang,
> Thanks a lot. I reran using -c chr21 -cut 2000 and it worked fine.
> Is it possible that the input bedpe files were too big(20+G) so it crashed before finishing the p-values calculating? The input files are HiC data. Would specifying less eps parameters help?

Dear User,
What is the memory of you computer/server? If the memory are limited, then the crash could caused by the too big data.
However, from the estimated self-ligation vs. inter-ligation distance cutoff in the log file, I figure may be the data have a lot close PETs (such as within 10kb) ? I would suggest run -cut 2000 or 10000 for trial to get distant loops (also remove close PETs to save memory). Otherwise if you want close loops, then keep -cut small.
If you could give the chr21 data, I can adjust a parameter for you.
If you find cLoops nice for your data, please give us a star at github and cite it~
Best,
Yaqiang
